### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by chaps** [donautech/behaiv-remote-kernel#16]
As a `behaiv-remote-kernel` developer I want to add a python `requirements.txt` file so that I can install dependencies by referencing this file via `pip -r`.

Acceptance criteria :
- requirements.txt file contains the project dependencies
- current unittests do not fail after installing the requirements

**Comment by chaps** [comment]
Pull request to add requirements.txt file: https://github.com/donautech/behaiv-remote-kernel/pull/17

**Comment by Zoxon470** [comment]
I have already created a folder with dependencies in https://github.com/donautech/behaiv-remote-kernel/pull/15

This commit - https://github.com/donautech/behaiv-remote-kernel/pull/15/commits/11372369e1ceb2d703773fcb7262fc07614389e5

**Comment by dmi3coder** [comment]
@Zoxon470 yes, but I don't think that's all requirements, it gives ability to run the project but we have more dependencies in some of a `routes.py`. That's why we have separate ticket. But I like your structure for prod/dev separation with a base file.
Also, some developers just want to run `pip install requirements.txt` so we need to keep one in the root if needed. Maybe we can redirect them on `development.txt`?

**Comment by dmi3coder** [comment]
@chaps can you please have a look at this one?
https://github.com/donautech/behaiv-remote-kernel/pull/17#issuecomment-538718007

**Comment by chaps** [comment]
Hey, @dmi3coder  . 

Sorry it looks like it's already merged , 
I'm used to just adding the dependencies imported directly in the source "parent dependencies" (that is as to why I included very few of them), which when they get resolved and installed,  each dependency will pull their own dependencies , however your requirements.txt will make sure to pin all dependencies.
it LGTM :+1:

**Comment by dmi3coder** [comment]
@chaps @Zoxon470  I'll do a pr for dependencies in near future, thank you for help :)
